### ISSUE TITLE
Register for pip install

### ISSUE THREAD

**Issue by me25hage** [mattbellis/h5hep#7]
Make sure we have everything and find commands needed to register

**Comment by me25hage** [comment]
1. README.txt

"To accomodate Windows users, your “read me” file should include a .txt extension, and it should use Windows-style carriage returns. Just because you use a fancy text editor that runs from the command line and includes its own macro language, that doesn’t mean you need to make life difficult for your users. (Your users use Notepad. Sad but true.) Even if you’re on Linux or Mac OS X, your fancy text editor undoubtedly has an option to save files with Windows-style carriage returns."

**Comment by me25hage** [comment]
2. scripts folder should have same name as root directory (h5hep) and should have __init__.py

"Just put the httplib2 directory in the root directory, so you have an __init__.py file within an httplib2/ directory within the httplib2/ root directory" where httplib2 is h5hep

**Comment by me25hage** [comment]
3. docs directory 

The docs/ directory contains several .html and .css files and an images/ subdirectory, which contains several .png and .gif files. (This will be important later.) Also, in keeping with the convention for (l)gpl-licensed software, it has a separate file called COPYING.txt which contains the complete text of the lgpl."  Not sure what license we're using

**Comment by me25hage** [comment]
4. Steps for registering

python setup.py register sdist bdist_wininst upload
 - Register as a user and submit the package. When you release your project for the first time, Distutils will add your software to the Python Package Index and give it its own url. Every time after that, it will simply update the project metadata with any changes you may have made in your setup.py parameters.
- Press 2 to register as a new user or 1 to use existing log in

**Comment by mattbellis** [comment]
FWIW, here's a simple module that I use that can be installed from pip. So this person registered their stuff and some point I *assume* using this github layout. 

https://github.com/buckmaxwell/zipcode

**Comment by mattbellis** [comment]
I followed the procedure outlined at the link below and I think it works!

https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56
